services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33333:33333"  # La porta 33333 dell'host è mappata sulla 33333 del container
    environment:
      - NODE_ENV=TEST
    command: uvicorn main:app --host 0.0.0.0 --port 33333  # L'app in test usa la porta 3333

  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44444:44444"  # La porta 44444 dell'host è mappata sulla 4444 del container
    environment:
      - NODE_ENV=PRODUCTION
    command: uvicorn main:app --host 0.0.0.0 --port 44444  # L'app di produzione usa la porta 4444
