name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (se necessario)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            path/to/artifacts/**

      - name: Notify success
        run: echo "Release created!"
