name: Release

on:
  push:
    tags:
      - 'v*' # Attiva il workflow per qualsiasi tag che inizia con "v"

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

# non dobvrebbe servire
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }} # Nome del tag
          name: Release ${{ github.ref_name }}  # Nome della release
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify success
        run: echo "Release created!"
